### ISSUE TITLE
Memory Sessions

### ISSUE THREAD

**Issue by oleteacher** [steveattewell/gpt-3.5-turbo-with-memory#1]
Hello, nice script!

Experimenting with your chatgpt setup in classroom. Something I have noticed that sessions do not appear to be written.

Pretty sure there is nothing wrong with server settings, other scripts write sessions without issues.

Any suggestions where to start debugging issue?

**Comment by steveattewell** [comment]
Thanks, I spotted a few bugs in the conversation "memory" when it gets full sometimes, but not sure why you might not be getting $_SESSION['conversations'] filling up with "conversation!

Having said that...
I've made some updates to fix a bug I found, and also added ?testmode=true to write out the whole conversation.

Grab the new script and call it repeatedly with ?testmode=true&text=tell%20me%20a%20joke and you should see a succession of poorly written jokes appear :)
Good luck

**Comment by oleteacher** [comment]
Thank you Steve.

I will give new version a try this afternoon.

Apprecate you taking a look at code again!

**Comment by oleteacher** [comment]
Working great! In test mode can see conversations.

Maybe I was mistaken, assumed that I would see the conversations locally in sessions (or cookies). No local sessions being written but that is fine.

But it is working:)

Thanks!

**Comment by steveattewell** [comment]
Ah, yes, "session" information in this sense ($_SESSION['some_variable_name']) is stored on the server rather than the browser. You have to call session_start() in every one of your scripts across your application before setting or reading session variables. Useful for passing info between scripts that you don't want (ID's, API Keys...) or don't need the client (browser) to see.

**Comment by oleteacher** [comment]
Thank you Steve, this has been a very good lesson:)
